// import * as Calendar from '@fullcalendar/core';
// import { Calendar } from '@fullcalendar/core';
// import dayGridPlugin from '@fullcalendar/daygrid';
// import timeGridPlugin from '@fullcalendar/timegrid';
// import listPlugin from '@fullcalendar/list';
// import interactionPlugin from '@fullcalendar/interaction';
// window.FullCalendar = Calendar;
// window.dayGridPlugin = dayGridPlugin;
// window.timeGridPlugin = timeGridPlugin;
// window.listPlugin = listPlugin;
// window.interactionPlugin = interactionPlugin;

// import * as Calendar from '../../node_modules/fullcalendar/index.global';
// // import dayGridPlugin from '@fullcalendar/daygrid';
// // import timeGridPlugin from '@fullcalendar/timegrid';
// // import listPlugin from '@fullcalendar/list';
// // import interactionPlugin from '@fullcalendar/interaction';
// window.FullCalendar = Calendar;
// // window.dayGridPlugin = dayGridPlugin;
// // window.timeGridPlugin = timeGridPlugin;
// // window.listPlugin = listPlugin;
// // window.interactionPlugin = interactionPlugin;
